#!/bin/bash

log=$(ls /var/spool/torque/server_logs/* | sort -h | tail -n 1)

echo "[$(date)] searching for unknown ips..."

new_ips=$(
    comm -1 -3 \
        <(pbsnodes | grep ^ip- | sort) \
        <({
            grep "svr_is_request" $log | \
                tail -n 100 | \
                cut -d";" -f6 | \
                awk '{print $7}' | \
                cut -d: -f1 | \
                sed 's/\./-/g' | \
                awk '{print "ip-"$0}' | sort | uniq
            }))

np=16

echo "[$(date)] searching for unknown ips... Done"

for ip in $new_ips ; do
    # echo "[$(date)] new ip found! : $ip --- sending a ping"
    if ping -c 1 -q $ip &> /dev/null
    then
        echo "[$(date)] new ip found! : $ip --- node alive! adding a node [np=$np]"
        qmgr -c "create node $ip np=$np"
    fi
done
