#!/bin/bash

pbsnodes -l down | awk '{print $1}' | while read l ; do
    if [ $l == $(hostname) ]
    then
        echo "[$(date)] Do not delete the server node (skipping)"
    else
        echo "[$(date)] Deleting node $l : rerunning jobs"
        $(dirname $0)/qgrep $l | xargs qrerun -f
        echo "[$(date)] Deleting node $l : deleting node"
        qmgr -c "delete node $l"
    fi
done
