#!/bin/bash

pbsnodes -l down | awk '{print $1}' | while read l ; do
    if [ $l == $(hostname) ]
    then
        echo "[$(date)] Do not delete the server node (skipping)"
    else
        echo "[$(date)] Deleting node $l"
        sudo qmgr -c "delete node $l"
    fi
done
