#!/bin/bash
#-*- mode:sh -*-

PARALLEL=false
SUDO=false
SUDO_PASSWORD=
VERBOSE=true
while getopts ":qp-s:" opt
do
    case ${opt} in
        p)  PARALLEL=true ;
            echo "Invoking ssh in parallel."
            ;;
        s)  SUDO=true ;
            SUDO_PASSWORD=${OPTARG}
            echo "Enabling sudo."
            ;;
        -)  break ;;
        \?) OPT_ERROR=1; break;;
        * ) echo "unsupported option $opt" ;;
    esac
done

shift $(($OPTIND - 1))

stack=

while [[ $1 != "" && $1 != "--" ]]
do
    stack="$stack $1"
    shift
done

if [[ $1 == "--" ]]
then
    shift
    ssh_option="$stack"
    commands=$@
else
    ssh_option=""
    commands="$stack"
fi

hosts=$(cat $(dirname $0)/hosts | sed -e "s/#.*//g")

if $SUDO
then
    commands="echo $SUDO_PASSWORD | sudo -S -p \"\" -- sh -c \"$commands\""
fi
$VERBOSE && echo "Running command: $commands"
$PARALLEL && ssh_option="-t $ssh_option"

run (){
    ssh $ssh_option $host "cd $PWD; $commands"
}

for host in $hosts
do
    $VERBOSE && echo "logging in to $host..."
    if $PARALLEL
    then
        run &
    else
        run
    fi
done

wait
