#!/bin/bash

queue=$(qstat -Q | tail -n +3 | awk '{print $1}')
echo "queue: $queue"
nodect=$(pbsnodes | awk '/np/{sum+=$3}END{print sum}')
echo "nodect: $nodect"

if [ $($(dirname $0)/qgrep | wc -w) -lt 2000 ]
then
    echo "[$(date)] not enough jobs; holding and releasing all jobs"
    resched_num=2000
else
    resched_num=$((nodect*5))
fi

echo "[$(date)] picking $resched_num jobs"

jobs=$($(dirname $0)/qgrep | head -n $resched_num)

echo "[$(date)] holding"

qhold $jobs

echo "[$(date)] rescheduling"

qrls $jobs

echo "[$(date)] rescheduling done"
