#!/bin/bash

queue=$(qstat -Q | tail -n +3 | awk '{print $1}')
echo "queue: $queue"
nodect=$(pbsnodes | awk '/np/{sum+=$3}END{print sum}')
echo "nodect: $nodect"

period=${1:-30}
resched_num=$((nodect*5))
regex=Q

main (){
    echo "[$(date)] picking $resched_num jobs"

    jobs=$($(dirname $0)/qgrep $regex | head -n $resched_num)

    echo "[$(date)] holding"

    qhold $jobs

    echo "[$(date)] rescheduling"

    qrls $jobs

    echo "[$(date)] sleep $period"

    sleep $period
}

while :
do
    main
done

