#!/bin/bash

[ $USER != root ] && {
    echo "Must run as root " >&2
    exit 1
}



watch (){
    sec=$1
    shift
    while :
    do
        $(dirname $0)/$@
        sleep $sec
    done
}

trap 'kill $(jobs -p)' EXIT

for com in check-nodes delete-downs reschedule ; do
    watch 60 $com &
done

watch 30 check-sched &

wait

