#!/bin/bash

[ $USER != root ] && {
    echo "Must run as root " >&2
    exit 1
}

trap 'kill $(jobs -p)' EXIT
$(dirname $0)/reschedule 60 &
$(dirname $0)/watch-sched 60 &
$(dirname $0)/watch-new-nodes 60 &

wait
