#!/bin/bash

sec=${1:-60}

echo "Watching PBS scheduler & server once per $sec sec!"

while :
do
    if ! pgrep pbs_sched &> /dev/null
    then
        echo "$(date): pbs_sched died, restarting!"
        service torque-scheduler start
    fi
    if ! pgrep pbs_server &> /dev/null
    then
        echo "$(date): pbs_server died, restarting!"
        service torque-server start
    fi
    sleep $sec
done
